development:
  clients:
    default:
      database: sample_app_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

test:
  clients:
    default:
      database: sample_app_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

production:
  clients:
    default:
      uri: <%=Rails.application.secrets.uri%>
      options:
        server_selection_timeout: 5
